apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-frontend-service
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
    app: todo-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
      {{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort | default "" }}
      {{- end }}
  selector:
    {{- include "todo-chatbot.selectorLabels" . | nindent 4 }}
    app: todo-frontend