{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-database
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
    app: todo-postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "todo-chatbot.selectorLabels" . | nindent 4 }}
    app: todo-postgres
{{- end }}